### ISSUE TITLE
Add percentage to the main statistics of confirmed, active, recovered and deceased

### ISSUE THREAD

**Issue by friendlychirag** [someshkar/covid19india-cluster#113]
Please Add percentage to the main statistics of confirmed, active, recovered and deceased so that the stats can be used and compared for various purposes

**Comment by friendlychirag** [comment]
Please Add percentage to the main statistics of confirmed, active, recovered and deceased so that the stats can be used and compared for various purposes

**Comment by sibeshkar** [comment]
Issue belongs to https://github.com/covid19india/covid19india-react
