### ISSUE TITLE
Consider migrating the db

### ISSUE THREAD

**Issue by thatcashcow** [someshkar/covid19india-cluster#119]
**Is your feature request related to a problem? Please describe.**
The limitations of google sheet are given here:
https://spreadsheetpoint.com/google-sheets-limitations/
With a limit of 5 million cells, we need a better storage solution for the huge incoming data.

**Describe the solution you'd like**
Consider exporting the data to json based NoSQL/SQL or other similar formats. If you lack a hosting provider you can always have a donation page for paying the server costs.

**Comment by sibeshkar** [comment]
So our API is caching spreadsheet data ever hour and making it available. So it's not really polling it in real time. More here : https://github.com/amodm/api-covid19-in

**Comment by thatcashcow** [comment]
Good to know. This might be helpful
https://covid-19-apis.postman.com/ in case you'd like to submit the API there.
