### ISSUE TITLE
Add a legend for colors

### ISSUE THREAD

**Issue by someshkar** [someshkar/covid19india-cluster#12]
The fact that colors correspond to status isn't clear to people. This needs to be shown somewhere-

- Green: Recovered
- Orange: Hospitalized
- Red: Deceased

**Comment by jainAdijain** [comment]
There are  legends right now...
Currently - 
1. Confirmed - Red
2. Active - Blue
3. Recovered - Green
4. Deceased - Grey

Hopitalized is not present in the UI..?
Is thi fixed or something else needs to be added?



1.

**Comment by someshkar** [comment]
@jainAdijain The blue markers are for districts, not for any type of patients.

**Comment by shubh0107** [comment]
I've already lodged a PR for this.

**Comment by itguyofficial** [comment]
this issue got fixed??

**Comment by shubh0107** [comment]
Yes.

**Comment by Lord-V15** [comment]
@someshkar Shouldn't this issue be closed?

**Comment by someshkar** [comment]
Yeah, this got fixed. Closing.
