### ISSUE TITLE
ADD SOME NEW FEATURE(MUST).

### ISSUE THREAD

**Issue by Kalibaba-Pro** [someshkar/covid19india-cluster#120]
Can you add Some New Feature For Patients  Like :- Name . If You Do like P144:- Name:- XYZ, Tht Type  Of Feature Much Better Than As Compared To Other Website. If You Do Add That feature Than Other Person Allate For Precaution, He Was Contact With That Person Or Not. Before He Going To Test For COVID_19.Our Country Have Different Type Of Festival And We Join It Very Well There Festival Like Marriage,Receptions,Birthday etc. If We Know There are Name Then We Can Avoid To Go There & Keep The Safe Distance Or We Can Know About Person.    

💯 %
#Kalibaba-Pro
#2
@sibeshkar

**Comment by sibeshkar** [comment]
Cannot include personal data in our graph.
