### ISSUE TITLE
Not able to search patient in cluster after P912

### ISSUE THREAD

**Issue by ajaykush2492** [someshkar/covid19india-cluster#149]
Steps to reproduce an issue:
- Go the cluster tab.
- Type P912 or above

**Comment by lovewithmind** [comment]
The [api](https://api.rootnet.in/covid19-in/unofficial/covid19india.org) is giving 911 records only as of now.

@sibeshkar might have to check the backend api

**Comment by sibeshkar** [comment]
Ah i see. Can you open a quick issue at : https://github.com/amodm/api-covid19-in ? That is the source of the API.

**Comment by lovewithmind** [comment]
Opened an issue https://github.com/amodm/api-covid19-in/issues/14 for this.

**Comment by sampathBlam** [comment]
@ajaykush2492 , @lovewithmind : The api seems to be fixed. 
Please close this issue.
