### ISSUE TITLE
Age-wise distribution of "confirmed", "active", "recovered", "death".

### ISSUE THREAD

**Issue by imflash217** [someshkar/covid19india-cluster#186]
**Is your feature request related to a problem? Please describe.**
Showing the distribution (using a plot similar to what's shown in the homepage) according to the `age` of various `confirmed`, `active`, `recovered` & `death` classes. All the data needed for such distribution is already present in the **spreadsheet**.

**Describe the solution you'd like**
This is a simple line plot which does not require any extra pre-processing except for cases whose age is not defined in the database.
⚠️  Don't count the people whose age is not defined in the spreadsheet.

**Describe alternatives you've considered**
As I can't download the spreadsheet it's cumbersome and error-prone to manually look and see for each data. But I will do it anyways and post a pull request.

**Additional context**
I am very willing to help, but we don't have access to download the spreadsheet so that I can work on it and send a pull request. Can the team help with this!

Thank you

**Comment by vinaykumar2491** [comment]
Another distribution could be based on Gender-wise. Having more better representation would be helpful always.
Also, these data are already displayed in the "clusters" section but is not very well organized.
