### ISSUE TITLE
CLUSTERS ARE LAGGING IN CITIES MODE

### ISSUE THREAD

**Issue by ArvindAROO** [someshkar/covid19india-cluster#189]
Due to heavy traffic and local calculation the city mode of clusters it's lagging a lot. I have tried a method of making a calculation on server and dorectly releasing the model than let it grow and expand into the correct cluster

**Comment by keepitopen** [comment]
Maybe switching to a state-wise view of the cities can help. Explaination: City-view only work on selecting a particular state. On clicking the city mode, the site can prompt the user to select a state(through the nodes). However, the problem then arises of the connections between patients of different cities(also states). This can be solved by having those patient nodes show an originating line with no end but on selecting that person(or clicking the line), a zoomed view of only that patients in relation shows up along with his city, state and any other connections of that patients if whatsoever.

**Comment by sibeshkar** [comment]
Possible solution here : https://github.com/someshkar/covid19india-cluster/issues/183
