### ISSUE TITLE
Regarding Clustering for setting red zone area and protecting non affected person

### ISSUE THREAD

**Issue by bpkapkar** [someshkar/covid19india-cluster#196]
**Is your feature request related to a problem? Please describe.**
This feature is related to clustering and tracking the patient visit and notifying other person if he has been in contact with that person

**Describe the solution you'd like**

I will like to recommend google map location service , where google can track and have the location of each of us as most of the people are android user(even ios track the location) . With the permission of the google in this critical condition we can get all the details of the location of patient's visit, on the basis of that we can notify other people ,who are/were around him.
With this people will have metrics about their potential being getting affected and they will become more sensible and alert.

 The person can be one node who has affected with the covid -19 and all other will be branches who has visited to same place at same time and other will sub branches who has came in contact with this kind of person.

**Describe alternatives you've considered**
Whats-app can also be used for notification  and tracking location and other payment apps can be used to know whom he has been in contact with and location he has visited on the basis of the payment and visited shops.

**Additional context**
Reference link: https://youtu.be/T1cb0Vvhv88
Above link can give detail idea ,how we can leverage technology in such crisis

**Comment by sibeshkar** [comment]
Good idea, but this seems out of the scope of this project
