### ISSUE TITLE
Confirmed number in Data table is not correct

### ISSUE THREAD

**Issue by akaura** [someshkar/covid19india-cluster#74]
The actual confirmed number (at current time) is 657. But datatable (list by state) total shows 602 which is equal to active number. 

"Confirmed" column = "Actual" + "Recovered" + "Deaths" 
![Screen Shot 2020-03-25 at 17 28 50](https://user-images.githubusercontent.com/24668137/77598075-1d249600-6ebe-11ea-8b00-d6eeb887079b.png)

**Comment by sibeshkar** [comment]
Leave issue at https://github.com/covid19india/covid19india-react
