### ISSUE TITLE
Cluster view - Patients chaining in chronological order

### ISSUE THREAD

**Issue by achyuth-belgundi** [someshkar/covid19india-cluster#82]
In my view creating a map that shows how person the infection has spread from p2p in chronological order 

This can give an impression:
1. With janta curfew & lock down how much we have been able to control the spread

2. Therefore Why lockdown and staying at home is important

**Comment by sibeshkar** [comment]
You can click on the clusters and select patients to see which date which case was reported.

**Comment by achyuth-belgundi** [comment]
My point was not that. I was referring to graph that can have dates in road map and map person to person spread. This can also indicate how the infection was controlled on dates before and after Lock down days..
