### ISSUE TITLE
Entering https://www.covid19india.org/clusters in browser does not work

### ISSUE THREAD

**Issue by thatcashcow** [someshkar/covid19india-cluster#83]
**To Reproduce**
In any browser open a new tab and go to https://www.covid19india.org/clusters

**Expected behavior**
Cluster page should be visible

**Comment by steffyjohn** [comment]
@thatcashcow  It is working fine when you open that in a new tab

**Comment by thatcashcow** [comment]
Strange. Yes its working now.
