### ISSUE TITLE
Last Updated Value seems to be hard coded

### ISSUE THREAD

**Issue by steffyjohn** [someshkar/covid19india-cluster#91]
![COVID 19 India Network-cluster](https://user-images.githubusercontent.com/45359124/77648387-16fdea80-6f8e-11ea-994c-ea707d8ace16.png)

The 2h ago update seems to be hard coded

**Comment by someshkar** [comment]
It is, yes. This can easily be fixed though, since [the API](https://api.rootnet.in) returns a last updated key too.

**Comment by gurumukhi** [comment]
I'm working on the fix.

**Comment by gurumukhi** [comment]
Raised PR - https://github.com/someshkar/covid19india-cluster/pull/121

**Comment by sibeshkar** [comment]
Fixed in https://github.com/someshkar/covid19india-cluster/pull/121
