### ISSUE TITLE
Population :: Add a new column against each state mentioning the population or Cases/1M population

### ISSUE THREAD

**Issue by archana900** [someshkar/covid19india-cluster#95]
Add a new column against each state mentioning the population or Cases/1M population.

This will tell how badly the state is hit.

**Comment by someshkar** [comment]
Is this really required? You can see a detailed breakdown of the number of cases in each state on the [main website](https://www.covid19india.org).

**Comment by archana900** [comment]
I meant main website... Opened issue # 209
